---
# from https://jekyllrb.com/docs/continuous-integration/travis-ci/

language: ruby
rvm:
- 2.3.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./.ci/build

# speed up installation of html-proofer
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=tru

sudo: false

exclude:
  - vendor

after_success:
  - openssl aes-256-cbc -K $encrypted_4d494b0e92ab_key -iv $encrypted_4d494b0e92ab_iv -in .ci/deploy_key.pem.enc -out .ci/deploy_key.pem -d
  - echo 'enospc.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCx3uSDW/WL8IciBIsoIohJzU36YVfOB7RagS69b61R2j+h2YiXzL16MNPm4DN2aSsz9QY2BsNu3zrHOWgT5U2yfLY+17dFf+xRcTutUoJ9yOatrqZk1i84xmrKiFtTNTy/YLXL4mSRf6pXhOjVN1nURHo6JZo1g+lRaVTOCYbXbwuRZizhI7nFw+lSgYb9IjVl+XdNl6faADo0TaKI+hYkGdOVl5o/fg4qYuFetjm4pmtA9zz0yHiBSUonQwipaZuoY/dK7F8le7AHokwYBDqRgNrxkPquV3iyOo7frzjrMZ1bAC6TzXglzUM1hTVd12pbXEFtt+xzj5CZNrGI5B4v' >> $HOME/.ssh/known_hosts
  - echo 'enospc.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBA6l2/mOMrp0gI/qB/YMDKVKSojoynkr52xDd7qO4yfTCnViY4EurnWhVWNKDzOGG+GpqAY7SvUIl62zfSCH9pw=' >> $HOME/.ssh/known_hosts
  - echo 'enospc.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOo1AADuJaxBKqZDpaEXxiJfBld0Rl8D4I7TQDH9OWcy' >> $HOME/.ssh/known_hosts
  - eval "$(ssh-agent -s)"
  - chmod 600 .ci/deploy_key.pem
  - ssh-add .ci/deploy_key.pem
  - rsync -av --delete $TRAVIS_BUILD_DIR/_site/ sites@enospc.org:/srv/nginx/nate.coraor.org/root
